server/app/mod_auth/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, current_user
from app.mod_auth.models import User
from app.mod_auth.forms import LoginForm, ChangePasswordForm
from app.common import login_exempt
import json

mod_auth = Blueprint('auth', __name__, url_prefix='/auth')

@mod_auth.route('/login', methods=['GET', 'POST'])
@login_exempt
def login():
	form = LoginForm(request.form)
	error = None
	
	if form.validate_on_submit():
		username = request.form['username']
		password = request.form['password']
		
		if 'rememberme' in request.form:
			rememberme = request.form['rememberme']
		else:
			rememberme = False
		
		user = User.query.filter_by(username=username).first()
		if user and user.check_password(password):
			login_user(user,remember=rememberme)
			return redirect(url_for('main.index'))
		else:
			error = 'Invalid username or password.'
	
	return render_template('auth/login.html', form=form, error=error)
	
@mod_auth.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('auth.login'))
	
@mod_auth.route('/status')
def status():
	return json.dumps({'Authenticated': True})

@mod_auth.route('/account', methods=['GET', 'POST'])
def account():
	form = ChangePasswordForm(request.form)
	error = None
	success = None
	
	if form.validate_on_submit():
		currentpassword = request.form['currentpassword']
		newpassword = request.form['newpassword']
		confirmpassword = request.form['confirmpassword']
		
		user = current_user
		if user.check_password(currentpassword):
			user.set_password(newpassword)
			success = 'Password has been changed.'
		else:
			error = 'Current password is incorrect.'
	
	templateData = {
		'apikey': current_user.apikey,
		'form': form,
		'error': error,
		'success': success
	}
	
	return render_template('auth/account.html', **templateData)
	
@mod_auth.route('/account/apikey')
def apikey():
	return json.dumps({'apikey': current_user.apikey})
	
@mod_auth.route('/account/apikey/generate')
def generateapikey():
	current_user.generateApiKey()
		
	return redirect(url_for('auth.account'))

@mod_auth.route('/account/apikey/delete')
def deleteapikey():
	current_user.deleteApiKey()
	
	return redirect(url_for('auth.account'))

server/app/mod_controlpanel/controllers.py
from flask import Blueprint, render_template, Response, make_response, redirect, url_for
from app.mod_controlpanel.models import Image
from app.common import doVisualRecognition, deleteFile, getConfigCamera, getImage, getStreamStatus
from app.dynamodblib import DecimalEncoder
from app.mqttlib import setLEDValue, setProcessValue
import app.mod_main as main_mod
import app.mod_controlpanel as controlpanel_mod
import json
import base64
import app
import time

mod_controlpanel = Blueprint('controlpanel', __name__, url_prefix='/controlpanel')

@mod_controlpanel.route('/')
def controlpanel():
	stream_address = getConfigCamera()['stream_address']
	rooms = app.rooms
	
	templateData = {
		'stream_address': stream_address,
		'rooms': rooms
	}
	
	return render_template('controlpanel/controlpanel.html', **templateData)
	
@mod_controlpanel.route('/stream')
def streamstatus():
	return json.dumps({'Status': getStreamStatus()})
	
@mod_controlpanel.route('/room', defaults={'room': None})
@mod_controlpanel.route('/room/<room>')
def room(room):
	rooms = app.rooms
	
	if room in rooms:
		rpi = rooms[room]
		response = json.dumps(rpi.getControlsData())
	else:
		response = ('',404)
		
	return response
	
@mod_controlpanel.route('/room/emit', defaults={'room': None, 'socketid': None})
@mod_controlpanel.route('/room/emit/<room>/<socketid>')
def roomemit(room,socketid):
	rooms = app.rooms
	
	if room in rooms:
		rpi = rooms[room]
		app.socketio.emit(room,rpi.getControlsData(),room=socketid)
		response = ('',204)
	else:
		response = ('',404)
		
	return response
	
@mod_controlpanel.route('/room/<room>/led/<int:pin>/set/mode/<int:value>')
def setLEDmode(room,pin,value):
	value = value == 1
	setLEDValue(room,pin,None,value)
	
	return ('',204)

@mod_controlpanel.route('/room/<room>/led/<int:pin>/set/<int:value>')
@mod_controlpanel.route('/room/<room>/led/<int:pin>/set/<float:value>')
def setLED(room,pin,value):
	setLEDValue(room,pin,value,True)
	
	return ('',204)
	
@mod_controlpanel.route('/room/<room>/process/<process>/set/<value>')
def setProcess(room,process,value):
	setProcessValue(room,process,value)
	
	return ('',204)
	
@mod_controlpanel.route('/camera/image/<int:id>/visualrecognition')
def visualrecognition(id):
	image = Image.query.get(id)
	
	if image:
		img = image.image
		
		timestring = time.strftime("%Y%m%d%H%M%S", time.gmtime())
		filename = 'image_{}.jpg'.format(timestring)

		with open(filename,'wb') as file:
			file.write(img)
			
		results = doVisualRecognition(filename)
		deleteFile(filename)
		
		classes = None
		try:
			classes = results['images'][0]['classifiers'][0]['classes']
		except:
			pass
		
		if classes:
			image.results = json.dumps(classes)
			image.save()
	
			response = ('',204)
		else:
			response = ('',503)
	else:
		response = ('',404)
	
	return response
	
@mod_controlpanel.route('/camera/image', defaults={'id': None})
@mod_controlpanel.route('/camera/image/<int:id>')
def camera_image(id):
	image = Image.query.get(id)
	
	if image:
		img = image.image
		response = make_response(img)
		response.headers['Content-Type'] = 'image/jpeg'
	else:
		response = ('', 404)
		
	return response
	
@mod_controlpanel.route('/camera/image/delete', defaults={'id': None})
@mod_controlpanel.route('/camera/image/delete/<int:id>')
def delete_image(id):
	image = Image.query.get(id)
	
	if image:
		image.delete()
		
	return ('',204)
	
@mod_controlpanel.route('/camera/image/<int:id>/details')
def camera_details(id):
	image = Image.query.get(id)
	
	if image:
		timestamp = image.timestamp
		results = image.results
		
		response = json.dumps({
			'ID': id,
			'Timestamp': timestamp,
			'Results': results
		}, cls=DecimalEncoder)
	else:
		response = ('', 404)
		
	return response
	
@mod_controlpanel.route('/camera/capture')
def camera_capture():
	img = getImage()
	
	if img:
		timestamp = time.time()
		image = Image(timestamp,img)
		image.add()
		
		response = json.dumps({'ID':image.id})
	else:
		response = ('', 503)
		
	return response
	
@mod_controlpanel.route('/camera/history')
def camera_history():
	images = Image.query.all()
	
	list = []
	for r in images:
		id = r.id
		timestamp = r.timestamp
		results = r.results
		
		if results:
			results = json.loads(results)
		
		d = {
			'ID': id,
			'Timestamp': timestamp,
			'Results': results
		}
		list.append(d)
		
	return json.dumps(list, cls=DecimalEncoder)

server/app/mod_settings/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.mod_settings.forms import AddRoomForm
from app.common import getSubscription, DeleteSensorTopic
from app.dynamodblib import DecimalEncoder, query, scan, putItem, deleteItem, updateItem
from app.mqttlib import roomSubscribe, roomUnsubscribe
from boto3.dynamodb.conditions import Key
from decimal import Decimal
import app
import json
import time

mod_settings = Blueprint('settings', __name__, url_prefix='/settings')

@mod_settings.route('/', defaults={'action': None})
@mod_settings.route('/<action>', methods=['GET', 'POST'])
def configuration(action):
	form = AddRoomForm(request.form)
	
	error = None
	success = None
	
	if form.validate_on_submit():
		if action == 'add':
			topic = request.form['topic']
			displayname = request.form['displayname']
			nightlevel = request.form['nightlevel']
			
			subscription = getSubscription(topic)
			if subscription:
				error = 'Topic already exist.'
			else:
				item = {
					'Topic': topic,
					'Timestamp': time.time(),
					'Displayname': displayname,
					'Nightlevel': Decimal(nightlevel)
				}
				r = putItem('Subscription',item)
				if r:
					roomSubscribe(topic)
					success = 'Added new room.'
				else:
					error = 'Unable to add subscription.'
		elif action == 'edit':
			topic = request.form['topic']
			displayname = request.form['displayname']
			nightlevel = request.form['nightlevel']
			
			subscription = getSubscription(topic)
			if subscription:
				key = {
					'Topic': topic
				}
				updateExpression = 'set Displayname = :d, Nightlevel=:n'
				expressionAttributeValues = {
					':d': displayname,
					':n': Decimal(nightlevel)
				}
				r = updateItem('Subscription',key,updateExpression,expressionAttributeValues)
				rooms = app.rooms
				if r and topic in rooms:
					rpi = rooms[topic]
					rpi.name = displayname
					success = 'Room edited.'
				else:
					error = 'Unable to edit subscription.'
			else:
				error = 'Topic does not exist.'
			
	templateData = {
		'form': form,
		'error': error,
		'success': success
	}
	
	return render_template('settings/configuration.html', **templateData)
	
@mod_settings.route('/subscription/delete', defaults={'topic': None})
@mod_settings.route('/subscription/delete/<topic>')
def deletesubscription(topic):
	if topic:
		subscription = getSubscription(topic)
		
		if subscription:
			topic = subscription['Topic']
			key = {
				'Topic': topic
			}
			r = deleteItem('Subscription',key)
			if r:
				roomUnsubscribe(topic)
				deleteSensorTopic = DeleteSensorTopic(topic)
				deleteSensorTopic.start()
		
	return ('',204)
	
@mod_settings.route('/subscription/json', defaults={'room': None})
@mod_settings.route('/subscription/json/<room>')
def subscriptionjson(room):
	if room:
		results = [getSubscription(room)]
	else:
		results = scan('Subscription')
	
	data = []
	
	if results:
		for s in results:
			data.append({
				'Topic': s['Topic'],
				'Timestamp': s['Timestamp'],
				'Displayname': s['Displayname'],
				'Nightlevel': s['Nightlevel']
			})
		
	return json.dumps(data, cls=DecimalEncoder)

server/app/templates/_chartoptions.html
<div class="clearfix">
	<div class="pull-right">
		<select class="form-control" id="chart_{{ id }}_zoom">
			<option value="1" selected>5m</option>
			<option value="2">30m</option>
			<option value="3">1H</option>
			<option value="4">1D</option>
			<option value="5">1W</option>
			<option value="6">1M</option>
			<option value="7">1Y</option>
			<option value="8">ALL</option>
		</select>
	</div>
</div>

server/app/templates/_header.html
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Smart Home</title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<!-- Bootstrap 3.3.7 -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
	<!-- Ionicons -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/ionicons.min.css') }}">
	<!-- Theme style -->
	<link rel="stylesheet" href="{{ url_for('static', filename='dist/css/AdminLTE.min.css') }}">
	<!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
	<link rel="stylesheet" href="{{ url_for('static', filename='dist/css/skins/_all-skins.min.css') }}">
	
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-table.min.css') }}">
	
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-toggle.min.css') }}">
	
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-slider.min.css') }}">
	
	<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}">
	
	<link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

	<!-- Google Font -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

server/app/templates/_modalconfirm.html
<div id="confirm_modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Confirmation</h4>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete "<span id="confirm_modal_name"></span>" (ID=<span id="confirm_modal_id"></span>)?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            <button type="button" class="btn btn-danger" id="confirm_modal_submit">Yes</button>
        </div>
        </div>
    </div>
</div>

server/app/templates/_navbar.html
<!-- Main Header -->
<header class="main-header">
    <!-- Logo -->
    <a href="{{ url_for('main.index') }}" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><b>LTD Smart Home</b></span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b>LTD Smart Home</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" id="sidebar-toggle" data-toggle="push-menu" role="button">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>

		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="{{ url_for('auth.account') }}"><i class="fa fa-user" aria-hidden="true"></i> Account</a></li>
						<li><a href="{{ url_for('auth.logout') }}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
						<li class="divider"></li>
						<li><a href="javascript:clearCookies()"><i class="fa fa-trash" aria-hidden="true"></i> Clear Cookies</a></li>
					</ul>
				</li>
			</ul>
		</div>
    </nav>
</header>

<!-- =============================================== -->

<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar" id="navbar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<ul class="sidebar-menu" data-widget="tree">
			<li class="header">NAVIGATION</li>
			<li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard" aria-hidden="true"></i> <span>Dashboard</span></a></li>
			<li><a href="{{ url_for('controlpanel.controlpanel') }}"><i class="fa fa-desktop" aria-hidden="true"></i> <span>Control Panel</span></a></li>
			<li><a href="{{ url_for('settings.configuration') }}"><i class="fa fa-cog" aria-hidden="true"></i> <span>Configuration</span></a></li>
		</ul>
	</section>
	<!-- /.sidebar -->
</aside>

server/app/templates/_scripts.html
<script type="text/javascript" src="{{ url_for('static', filename='js/loader.js') }}"></script>

<!-- jQuery 3 -->
<script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>

<!-- Bootstrap 3.3.7 -->
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

<!-- FastClick -->
<script src="{{ url_for('static', filename='js/fastclick.js') }}"></script>

<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='dist/js/adminlte.min.js') }}"></script>

<!-- SlimScroll -->
<script src="{{ url_for('static', filename='js/jquery.slimscroll.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-table.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/js.cookie-2.1.4.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-toggle.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-slider.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/clipboard.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/handlebars-v4.0.10.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/socket.io.js') }}"></script>

<script>
	$(document).ready(function(){
		var currentPage = window.location.pathname;
		$("#navbar ul li a[href='" + currentPage + "']").parent().addClass("active");
		
		$('[data-toggle="tooltip"]').tooltip({
			container: 'body'
		});
	});
</script>

<script>
	function clearCookies() {
		Cookies.remove('refreshrate');
		Cookies.remove('zoom');
		
		alert('Cookies cleared');
		location.reload();
	}
	
	function initModalScroll(modal) {
        var body = modal.find('.modal-body');
        var height = $(window).height() * 0.7;

        body.slimscroll({
            destroy: true
        });

        body.slimscroll({
            height: height
        });
    }
	
	function formatDate(date) {
		var day = date.getDate();
		var month = date.getMonth() + 1;
		var year = date.getFullYear();
		
		var seconds = date.getSeconds();
		var minutes = date.getMinutes();
		var hour = date.getHours();
		
		var formatted = ('0' + day).slice(-2) + '-' + ('0' + month).slice(-2) + '-' + ('' + year).slice(-2) + ' ' + ('0' + hour).slice(-2) + ':' + ('0' + minutes).slice(-2) + ':' + ('0' + seconds).slice(-2);
		return formatted;
	}
	
	function utcTimestampToDate(timestamp) {
		var date = new Date(0);
		date.setUTCSeconds(timestamp);
		
		return date;
	}
	
	function showConfirmModal(e,ajax) {
		e = $(e);
		
		var id = e.attr('data-confirm-id');
		var name = e.attr('data-confirm-name');
		var url = e.attr('data-confirm-url');
		var table = e.attr('data-confirm-table');
		
        var confirm_modal = $('#confirm_modal');
        var confirm_modal_id = $('#confirm_modal_id');
        var confirm_modal_name = $('#confirm_modal_name');
        var confirm_modal_submit = $('#confirm_modal_submit');
		var confirm_modal_buttons = confirm_modal.find('.modal-footer .btn');
		
		confirm_modal_submit.off('click');

        confirm_modal_id.html(id);
        confirm_modal_name.html(name);
		
		confirm_modal_submit.click(function () {
			confirm_modal_buttons.prop('disabled',true);
			
			if (ajax) {
				$.ajax({
					url: url,
					success: function(result) {
						confirm_modal.modal('hide');
						$('#' + table).bootstrapTable('refresh',{silent: true});
					},
					complete: function() {
						confirm_modal_buttons.prop('disabled',false);
					}
				});
			} else {
				window.location.replace(url);
			}
		});
		
        confirm_modal.modal();
    }
	
	function isArrayInArray(arr, item){
		var item_as_string = JSON.stringify(item);

		var contains = arr.some(function(e){
			return JSON.stringify(e) === item_as_string;
		});

		return contains;
    }
	
	function socketConnect() {
		socket = io.connect('wss://' + document.domain + ':' + location.port);
		return socket;
	}
</script>